spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: pig-auth
          uri: lb://cloud-author
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
     
        - id: cloud-account
          uri: lb://cloud-account
          predicates:
            - Path=/server/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # 代码生成模块
        - id: pig-codegen
          uri: lb://cloud-codegen
          predicates:
            - Path=/gen/**
security:
  encode:
    # 前端密码密钥，必须16位
    key: 'thanks,zoucloud'

# 不校验验证码终端
ignore:
  clients:
    - test
